# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_Laplace <- function(lat0, v, K, PDcorrect, Dloglik, D2loglik, Qv) {
    .Call(`_mixcurelps_Rcpp_Laplace`, lat0, v, K, PDcorrect, Dloglik, D2loglik, Qv)
}

Rcpp_Laplace2 <- function(lat0, v, K, Dloglik, D2loglik, Qv) {
    .Call(`_mixcurelps_Rcpp_Laplace2`, lat0, v, K, Dloglik, D2loglik, Qv)
}

Rcpp_cubicBspline <- function(x, lower, upper, K) {
    .Call(`_mixcurelps_Rcpp_cubicBspline`, x, lower, upper, K)
}

